import Link from "next/link"
import { AnimatedGrid } from "@/components/animated-grid"
import { Button } from "@/components/ui/button"
import { ArrowLeft } from "lucide-react"

export default function TermsPage() {
  return (
    <main className="relative min-h-[100dvh] overflow-hidden p-3 md:p-8">
      <AnimatedGrid />

      <div className="relative z-10 mx-auto max-w-4xl pt-4 md:pt-10 pb-6">
        <div className="mb-6 flex flex-wrap items-center gap-3">
          <Link href="/">
            <Button variant="ghost" className="text-primary hover:bg-primary/10">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back
            </Button>
          </Link>
        </div>

        <section className="rounded-2xl border bg-white/70 p-4 sm:p-6 shadow-sm backdrop-blur-sm md:p-10">
          <p className="mb-2 text-xs uppercase tracking-[0.22em] text-primary/80">Terms & Conditions</p>
          <h1 className="mb-4 text-2xl sm:text-3xl font-bold tracking-tight text-foreground md:text-5xl">Test Phase Notice</h1>

          <div className="space-y-4 text-sm leading-7 text-muted-foreground md:text-base">
            <p>
              Sahrdaya RAGx is currently in test phase (v1). Responses may contain inaccuracies, outdated details,
              or missing information.
            </p>
            <p>
              The assistant is provided for informational purposes only. Do not make critical personal, academic,
              financial, legal, medical, or administrative decisions based only on AI responses.
            </p>
            <p>
              By using this test system, you acknowledge that the project team is not responsible for decisions,
              actions, or outcomes resulting from information generated by the AI.
            </p>
            <p>
              Always verify important details through official college channels before acting.
            </p>
          </div>
        </section>
      </div>
    </main>
  )
}
