"use client"

import { useEffect, useState } from "react"
import { useSearchParams } from "next/navigation"
import { AnimatedGrid } from "@/components/animated-grid"
import { ChatInterface } from "@/components/chat-interface"
import { StatusIndicator } from "@/components/status-indicator"
import { Button } from "@/components/ui/button"
import FooterTime from "@/components/footer-time"
import Link from "next/link"
import {
  MessageSquare,
  ArrowLeft,
  Sparkles,
} from "lucide-react"

export default function ChatPage() {
  const searchParams = useSearchParams()
  const initialMessage = searchParams.get("q") || undefined
  const [checkingConsent, setCheckingConsent] = useState(true)
  const [hasConsent, setHasConsent] = useState(false)
  const [agreeChecked, setAgreeChecked] = useState(false)

  useEffect(() => {
    try {
      const accepted = window.localStorage.getItem("ragx_terms_accepted") === "true"
      setHasConsent(accepted)
    } finally {
      setCheckingConsent(false)
    }
  }, [])

  const acceptTerms = () => {
    if (!agreeChecked) return
    window.localStorage.setItem("ragx_terms_accepted", "true")
    setHasConsent(true)
  }

  return (
    <main className="relative h-[100dvh] overflow-hidden">
      <AnimatedGrid />

      {/* Header */}
      <header className="fixed top-0 left-0 right-0 h-14 md:h-16 bg-white/50 backdrop-blur-sm border-b flex items-center justify-between px-3 md:px-6 z-50">
        <div className="flex items-center gap-2 md:gap-4 min-w-0">
          <Link href="/">
            <Button
              variant="ghost"
              size="sm"
              className="text-muted-foreground hover:text-foreground"
            >
              <ArrowLeft className="w-4 h-4 mr-1" />
              Back
            </Button>
          </Link>
          <div className="flex items-center gap-2 text-primary font-semibold">
            <Sparkles className="w-4 h-4" />
            <span className="text-xs sm:text-sm">RAGx Chat</span>
          </div>
        </div>
        <div className="hidden sm:block">
          <StatusIndicator />
        </div>
      </header>

      {/* Main Content */}
      <div className="fixed top-14 md:top-16 bottom-12 left-0 right-0 px-2 sm:px-4 md:px-8 py-3 md:py-4 overflow-hidden">
        <div className="max-w-7xl mx-auto h-full overflow-hidden">
          <div className="h-full overflow-hidden">
            <div className="h-full overflow-hidden">
              {!checkingConsent && hasConsent ? (
                <ChatInterface initialMessage={initialMessage} />
              ) : (
                <div className="h-full flex items-center justify-center px-1 sm:px-0">
                  <div className="w-full max-w-lg rounded-2xl border bg-white/80 shadow-sm backdrop-blur-sm p-4 sm:p-6 md:p-8 max-h-full overflow-y-auto">
                    <h2 className="text-lg md:text-xl font-semibold text-foreground">Before You Enter Chat</h2>
                    <div className="mt-3 space-y-3 text-sm text-muted-foreground leading-6">
                      <p className="font-semibold text-foreground">
                        Sahrdaya RAGx is currently in test phase (v1). Responses may contain inaccuracies, outdated details,
                        or missing information.
                      </p>
                      <p className="font-semibold text-foreground">
                        The assistant is provided for informational purposes only. Do not make critical personal, academic,
                        financial, legal, medical, or administrative decisions based only on AI responses.
                      </p>
                      <p className="font-semibold text-foreground">
                        By using this test system, you acknowledge that the project team is not responsible for decisions,
                        actions, or outcomes resulting from information generated by the AI.
                      </p>
                      <p className="font-semibold text-foreground">Always verify important details through official college channels before acting.</p>
                    </div>
                    <p className="mt-3 text-sm text-muted-foreground">
                      Read terms: <Link href="/terms" className="text-primary underline underline-offset-4 hover:text-primary/80">/terms</Link>
                    </p>

                    <label className="mt-5 flex items-start gap-3 text-sm text-foreground">
                      <input
                        type="checkbox"
                        checked={agreeChecked}
                        onChange={(e) => setAgreeChecked(e.target.checked)}
                        className="mt-0.5 h-4 w-4 rounded border-border"
                      />
                      <span>I agree to the Terms & Conditions and understand this is a test-phase system.</span>
                    </label>

                    <div className="mt-6 flex flex-col sm:flex-row gap-3">
                      <Button
                        onClick={acceptTerms}
                        disabled={!agreeChecked}
                        className="bg-primary text-primary-foreground hover:bg-primary/90"
                      >
                        Continue to Chat
                      </Button>
                      <Link href="/">
                        <Button variant="outline" className="w-full sm:w-auto">Go Back</Button>
                      </Link>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="fixed bottom-0 left-0 right-0 h-12 bg-white/50 backdrop-blur-sm border-t flex items-center justify-between px-3 md:px-6 text-xs text-muted-foreground z-50">
        <div className="flex items-center gap-4">
          <span className="flex items-center gap-1">
            <MessageSquare className="w-3 h-3" />
            RAG Chat Interface
          </span>
        </div>
        <FooterTime />
      </div>
    </main>
  )
}
